### ISSUE TITLE
[HorseStats[ null

### ISSUE THREAD

**Issue by madtomic** [RedPanda4552/HorseStats#1]
no error but when an OP player logs in game.

In chat, it would say [HorseStats[ null

1.7.10 using HorseStats v3.3.1

**Comment by RedPanda4552** [comment]
It appears that the translation file you have is out of date. If your translation file is from a previous HorseStats version, then the plugin will not be able to properly find the strings. If you use English on your server, you should be fine just deleting the translate.yml file and doing a server reload or restart. Otherwise, you will need to copy-paste your old translations into the new file where appropriate.

**Comment by madtomic** [comment]
All the files are generated with v3.3.1

This is the default settings. It's all generated when loaded. No previous or old files was used.

**Comment by RedPanda4552** [comment]
Because you are running HorseStats v3.3.1 which is built for MC 1.8 on a MC 1.7.10 server, I can't guarantee that anything will work either. I don't have a copy of a 1.7.10 Bukkit server but on 1.7.9 the plugin can't even load because a method does not exist. Your options are either upgrade your server or downgrade HorseStats.
